version: "3"

services:
  cqs-pg-db:
    container_name: cqs-pg-db
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - /var/lib/postgresql/data/
    expose:
      - 5432
    ports:
      - "5432:5432"

  callback-test-app:
    container_name: callback-test-app
    image: ghcr.io/translatorsri/callback-test-app:0.1.0
    expose:
      - 8008
    ports:
      - "8008:8008"

  cqs-app:
    container_name: cqs-app
    build: .
    restart: always
    env_file: .env
    expose:
      - 8000
    ports:
      - "8000:8000"
    volumes:
      - "${WFR_OUTPUT_DIR}:/tmp/cqs"
    depends_on:
      - cqs-pg-db
      - callback-test-app

