-- Your SQL goes here
ALTER TABLE jobs ALTER COLUMN date_submitted TYPE TIMESTAMPTZ;
ALTER TABLE jobs ALTER COLUMN date_started TYPE TIMESTAMPTZ;
ALTER TABLE jobs ALTER COLUMN date_finished TYPE TIMESTAMPTZ;
